### ISSUE TITLE
Nether causes crash [1.17] [LilTaterReloaded-1.1.12+1.17-RUSHED-E3-EDITION]

### ISSUE THREAD

**Issue by KavisKryptic** [Yoghurt4C/LilTaterReloaded#10]
When testing in a creative world, I went into the nether portal and it caused a crash.

Here is the crash report:

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/15/21, 12:42 PM
Description: Exception ticking world

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_4836.method_18867(class_4836.java:261)
	at net.minecraft.class_1309.<init>(class_1309.java:251)
	at net.minecraft.class_1308.<init>(class_1308.java:121)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1588.<init>(class_1588.java:30)
	at net.minecraft.class_5418.<init>(class_5418.java:31)
	at net.minecraft.class_4836.<init>(class_4836.java:135)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at net.minecraft.class_1948.method_24931(class_1948.java:342)
	at net.minecraft.class_1948.method_24930(class_1948.java:271)
	at net.minecraft.class_1948.method_8663(class_1948.java:199)
	at net.minecraft.class_1948.method_27821(class_1948.java:187)
	at net.minecraft.class_3215.method_20801(class_3215.java:370)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_3215.method_14161(class_3215.java:354)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method ltr_lootTater(Lnet/minecraft/class_4836;Lnet/minecraft/class_1542;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)V in ltr.mixins.barter.json:PiglinBrainMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap LilTaterReloaded-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 29 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_4836.method_18867(class_4836.java:261)
	at net.minecraft.class_1309.<init>(class_1309.java:251)
	at net.minecraft.class_1308.<init>(class_1308.java:121)
	at net.minecraft.class_1314.<init>(class_1314.java:12)
	at net.minecraft.class_1588.<init>(class_1588.java:30)
	at net.minecraft.class_5418.<init>(class_5418.java:31)
	at net.minecraft.class_4836.<init>(class_4836.java:135)
	at net.minecraft.class_1299.method_5883(class_1299.java:475)
	at net.minecraft.class_1948.method_24931(class_1948.java:342)
	at net.minecraft.class_1948.method_24930(class_1948.java:271)
	at net.minecraft.class_1948.method_8663(class_1948.java:199)
	at net.minecraft.class_1948.method_27821(class_1948.java:187)
	at net.minecraft.class_3215.method_20801(class_3215.java:370)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_3215.method_14161(class_3215.java:354)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)

-- Affected level --
Details:
	All players: 1 total; [class_3222['KavisKrypt'/171, l='ServerLevel[New World]', x=2.30, y=65.42, z=7.61]]
	Chunk stats: 1477
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-48,66,48), Section: (at 0,2,0 in -3,4,3; chunk contains blocks -48,0,48 to -33,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2681 game time, 2681 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 47993 (now: false), thunder time: 41891 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1694055640 bytes (1615 MiB) / 4483710976 bytes (4276 MiB) up to 7885291520 bytes (7520 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6079
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37580.14
	Virtual memory used (MB): 18663.79
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 11.77
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7520m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		addendum: Addendum 1.0.2
		adorn: Adorn 2.0.0+1.17
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		amecsapi: Amecs API 1.1.5+mc21w16a
		apoli: Apoli 1.0.0
		architects_palette: Architect's Palette Fabric 1.1
		artifice: Artifice 0.15.3+21w07a
		backslot: BackSlot 1.1.12
		beaconoverhaul: Beacon Overhaul 1.4.0+1.17
		bedspreads: Bedspreads 1.4.0-1.17
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterf3: BetterF3 1.1.5
		betterthirdperson: Better Third Person 1.5.0
		biom4st3r_repackaged_expressions: expj4_repackaged 0.1.0
		biome_locator: Biome Locator 1.1.2
		bitsandchisels: BitsAndChisels 2.5.0
		blockus: Blockus 2.2.1+1.17
		blue_endless_jankson: jankson 1.2.1
		caelus: Caelus API 0.0.16-1.17
		calio: Calio 1.0.0
		cardinal-components: Cardinal Components API 3.0.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-block: Cardinal Components API (blocks) 3.0.0
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-item: Cardinal Components API (items) 3.0.0
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.0
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carrier: Carrier 1.8.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		comforts: Comforts 0.0.4-1.17
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		consistency_plus: Consistency Plus 0.3.3-build.261_UNMINIFIED
		croptopia: Croptopia ${mod_version}
		croptosis: Croptosis 1.1.2
		cullleaves: Cull Leaves 2.2.0
		darkpaintings: Dark Paintings 3.0.6
		dawn: Dawn API 2.0.3
		dual_riders: DualRiders 1.0.5
		ducts: Ducts 1.1.0
		dynmus: Dynamic Music 1.3.0
		earthtojavamobs: Earth2Java 1.7.1+1.17
		easyautocrafting: EasyAutoCrafting 1.1+1.17
		editsign: EditSign 2.2.1
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchant_giver: Enchant Giver 1.1.0
		entityculling: EntityCulling-Fabric 1.2.3
		expandedstorage: Expanded Storage 7.0.0-alpha.25
		fabric: Fabric API 0.35.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+1d383bb63d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c3d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fastchest: FastChest 1.2+1.17
		fastfurnace: FastFurnace 1.17-3.0
		flytre_lib: FlytreLib 0.2.13
		givemehats: Give Me Hats! 1.6
		greater_eye: Greater Eye of Ender 1.2.4
		grindenchantments: Grind Enchantments 1.1.4+1.17
		improved-stations: Improved Stations 2.0.5
		inventorysorter: Inventory Sorter 1.7.9-1.17
		invisiblights: InvisibLights 7.1+1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kibe: Kibe 1.7.2-BETA+1.17
		kirin: Kirin UI 1.8.7-1.17
		kyrptconfig: Kytpt Config 1.1.10-1.17
		libblockattributes: LibBlockAttributes 0.9.0-pre.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0-pre.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0-pre.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0-pre.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.0
		ltr: LilTaterReloaded 1.1.12+1.17
		mcda: MC Dungeons Armors 1.6.2
		mcdw: MC Dungeons Weapons 3.2.2-1.17
		mcsa: MC Story Mode Armor 2.3.2-1.17
		medievalweapons: Medieval Weapons 1.1.5
		minecraft: Minecraft 1.17
		mo_glass: Mo Glass 1.5-MC1.17
		mocolors: Mo' Colors 1.2.0
		modmenu: Mod Menu 2.0.0-beta.7
		moenchant_lib: Mo'Enchantment Library 0.1.0
		moenchantments: Mo'Enchantments 1.17.0
		morevillagers-fabric: MoreVillagersFabric 2.0.0-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-pre1+mc.1.17
		omega-config: OmegaConfig ${version}
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 1.0.0
		origins-classes: Origins: Classes 1.2.1
		packages: Packages 1.2.0
		pandamc_concreteplus: Concrete plus 1.8
		particle_emitter_biom4st3r: Particle Emitters LIB 0.1.0
		pipe: Pipe 1.3.1
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		seamless_loading_screen: Seamless Loading Screen 1.3.5+1.17
		secretrooms: Secret Rooms 1.0.0+1.17
		slotlock: SlotLock 1.0.4-BETA+1.17
		somnus: Somnus API 0.0.12-1.17
		stacc: Stacc 1.0.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		toolstats: Tool Stats 2.0.1
		transportables: Transportables 1.0.5
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		truerooms: True Secret Rooms 1.1.4
		tweed: Tweed API 3.0.0-beta.22
		universal_ores: Universal Ores 1.0
		voicechat: Simple Voice Chat 1.17-1.1.2
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.1
		xlpackets: XLPackets 1.1
	Player Count: 1 / 8; [class_3222['KavisKrypt'/171, l='ServerLevel[New World]', x=2.30, y=65.42, z=7.61]]
	Data Packs: vanilla (incompatible), secretrooms:server_pack, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by Yoghurt4C** [comment]
:)

**Comment by Yoghurt4C** [comment]
mojang changed their pigger methods again, sorry that I didn't test this extensively enough; seems to be working as intended in https://github.com/Yoghurt4C/LilTaterReloaded/commit/d7468ea5a17568fa41a70d1dc1c8aa1f15b69e0f.
now, the only piece of content that wasn't extensively tested should only be serverside networking - I'd appreciate it if you'd be willing to cooperate with that :)

**Comment by KavisKryptic** [comment]
> mojang changed their pigger methods again, sorry that I didn't test this extensively enough; seems to be working as intended in [d7468ea](https://github.com/Yoghurt4C/LilTaterReloaded/commit/d7468ea5a17568fa41a70d1dc1c8aa1f15b69e0f).
> now, the only piece of content that wasn't extensively tested should only be serverside networking - I'd appreciate it if you'd be willing to cooperate with that :)

Sure, I'd love to help anyway I can!
