### ISSUE TITLE
Server load failed due to critical injection failure

### ISSUE THREAD

**Issue by JuergenSchT** [Yoghurt4C/LilTaterReloaded#6]
When starting a server with LTR 1.1.9, server load stops and prints a bunch of errors. LTR 1.1.9 on the client works fine, however, even with the same mods installed.
There is no crash report generated.
```
[02:10:42] [main/INFO]: Loading for game Minecraft 1.16.3
[02:10:42] [main/INFO]: [FabricLoader] Loading 43 mods: minecraft@1.16.3, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, fabric-renderer-api-v1@0.3.1+f8ac1db295, fabric-screen-handler-api-v1@1.1.0+8724984195, fabric-keybindings-v0@0.2.0+3fa9f7c595, fabric-command-api-v1@1.0.8+5ce5339895, fabricloader@0.10.0+build.208, fabric-tool-attribute-api-v1@1.2.3+f8ac1db295, fabric-renderer-indigo@0.4.1+f8ac1db295, fabric-structure-api-v1@1.1.0+f8ac1db295, fabric-containers-v0@0.1.8+045df74f95, fabric-object-builder-api-v1@1.9.0+c270b09895, fabric-item-api-v1@1.2.0+f8ac1db295, fabric-events-interaction-v0@0.4.1+f8ac1db295, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-game-rule-api-v1@1.0.2+f8ac1db295, fabric-api-base@0.1.3+12a8474c95, fabric-rendering-v0@1.1.1+f8ac1db295, fabric-key-binding-api-v1@1.0.1+730711c695, fabric-rendering-v1@1.3.1+f8ac1db295, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db295, fabric-resource-loader-v0@0.3.1+facf3bbf95, fabric-textures-v0@1.0.4+eae12eb895, fabric-content-registries-v0@0.1.9+059ea86695, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, fabric-biome-api-v1@2.0.0+c29459ab95, fabric-rendering-fluids-v1@0.1.12+f8ac1db295, ltr@1.1.9+1.16.2, fabric-commands-v0@0.2.0+52d3083695, fabric-registry-sync-v0@0.5.2+3c53fe3395, openj9compat@1.0.1, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, fabric-mining-levels-v0@0.1.2+b764ce9995, fabric-renderer-registries-v1@2.2.0+f8ac1db295, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, fabric-loot-tables-v1@1.0.1+432ea18895, fabric@0.23.0+build.410-1.16, fabric-item-groups-v0@0.2.0+438f963695, fabric-models-v0@0.1.1+f8ac1db295, fabric-particles-v1@0.2.2+fb0d9b0e95, fabric-networking-v0@0.1.10+e00ecb5f95, fabric-object-builders-v0@0.7.0+432ea18895
[02:10:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/home/juergen/minecraftfabric3/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[02:10:49] [main/FATAL]: Mixin apply failed ltr.mixins.barter.json:PiglinEntityMixin -> net.minecraft.class_4836: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on ltr_getTaterAdmirationActivity could not find any targets matching 'Lnet/minecraft/class_4836;method_24705()Lnet/minecraft/class_4837;' in net.minecraft.class_4836. Using refmap LilTaterReloaded-refmap.json [PREINJECT Applicator Phase -> ltr.mixins.barter.json:PiglinEntityMixin -> Prepare Injections ->  -> handler$zbh000$ltr_getTaterAdmirationActivity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on ltr_getTaterAdmirationActivity could not find any targets matching 'Lnet/minecraft/class_4836;method_24705()Lnet/minecraft/class_4837;' in net.minecraft.class_4836. Using refmap LilTaterReloaded-refmap.json [PREINJECT Applicator Phase -> ltr.mixins.barter.json:PiglinEntityMixin -> Prepare Injections ->  -> handler$zbh000$ltr_getTaterAdmirationActivity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[fabric-server-launch.jar:?]
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_265]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_265]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881) [?:1.8.0_265]
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) [?:1.8.0_265]
	at java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:869) [?:1.8.0_265]
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:948) [?:1.8.0_265]
	at net.minecraft.class_1299.<clinit>(class_1299.java:214) [intermediary-server.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:27) [intermediary-server.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:62) [intermediary-server.jar:?]
	at net.minecraft.class_5464.<clinit>(class_5464.java:92) [intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30571(class_5458.java:46) [intermediary-server.jar:?]
	at net.minecraft.class_5458$$Lambda$218/0000000000000000.get(Unknown Source) [intermediary-server.jar:?]
	at net.minecraft.class_5458.md611747$lambda$staticInit$3$0(class_5458.java:551) [intermediary-server.jar:?]
	at net.minecraft.class_5458$$Lambda$210/0000000000000000.accept(Unknown Source) [intermediary-server.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_265]
	at net.minecraft.class_5458.handler$zbm000$staticInit(class_5458.java:550) [intermediary-server.jar:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:50) [intermediary-server.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-server.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-server.jar:?]
	at net.minecraft.server.Main.main(Main.java:88) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
```
(this not the complete log, the console spits more errors, but they don't appear in latest.log for some reason).

**Comment by Yoghurt4C** [comment]
![image](https://user-images.githubusercontent.com/11313954/96501991-da5f4c80-1259-11eb-9f2b-63e6a6b39a72.png)
unable to replicate in dev, might be a production bug

**Comment by Yoghurt4C** [comment]
it does the bad, investigating

**Comment by Yoghurt4C** [comment]
fixed in https://github.com/Yoghurt4C/LilTaterReloaded/commit/a0b0ef062a11f6229438faaf135adc9c8247cf68

**Comment by JuergenSchT** [comment]
TYSM Yoog, now my friends will learn to Love the Tater.
