### ISSUE TITLE
Crash on startup [1.17]

### ISSUE THREAD

**Issue by KavisKryptic** [Yoghurt4C/LilTaterReloaded#9]
I added the LilTaterReloaded mod to my modpack, but now I crash when launching unfortunately.

```
[17:11:08] [main/INFO]: Loading for game Minecraft 1.17
[17:11:08] [ForkJoinPool-1-worker-61/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[17:11:08] [ForkJoinPool-1-worker-39/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[17:11:08] [ForkJoinPool-1-worker-23/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[17:11:09] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b4463c6, also found 0.3.0+a02b4463d5, 0.3.0+a02b44633d, 0.3.0+a02b4463a0
 - Conflicting versions found for fabric-networking-v0: used 0.3.2+92519afac6, also found 0.3.2+92519afad5, 0.3.2+92519afa3d
 - Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab6121a0, also found 0.4.7+b7ab6121d5, 0.4.7+b7ab61213d
 - Conflicting versions found for fabric-tag-extensions-v0: used 1.1.4+a02b4463d5, also found 1.1.4+a02b44633d
[17:11:09] [main/INFO]: [FabricLoader] Loading 177 mods: fallflyinglib@3.0.0-beta.2, fabric-keybindings-v0@0.2.2+36b77c3e3d, cloth-common-events-v1@2.0.54, trinkets@3.0.0, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1, artifice@0.15.3+21w07a, morevillagers-fabric@2.0.0-SNAPSHOT, stacc@1.0.1, biom4st3r_repackaged_expressions@0.1.0, architects_palette@1.1, fabric-dimensions-v1@2.0.10+a02b44633d, kibe@1.7.2-BETA+1.17, java@16, apoli@1.0.0, fabric-game-rule-api-v1@1.0.6+a02b44633d, addendum@1.0.2, fabric-api-base@0.3.0+a02b4463c6, backslot@1.1.12, elytratrinket@2.0.1-1.17, consistency_plus@0.3.3-build.261_UNMINIFIED, cardinal-components-level@3.0.0-nightly.1.17-pre2, transportables@1.0.5, packages@1.2.0, org_jetbrains_kotlin_kotlin-stdlib@1.5.10, playerabilitylib@1.3.0-nightly.1.17-rc1, fabric-blockrenderlayer-v1@1.1.5+a02b44633d, mo_glass@1.5-MC1.17, libblockattributes_items@0.9.0-pre.2, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10, compostable-rottenflesh@1.0.0, dynmus@1.3.0, cardinal-components-scoreboard@3.0.0-nightly.1.17-pre2, fabric@0.35.2+1.17, fabric-networking-v0@0.3.2+92519afac6, dawn@2.0.2, flytre_lib@0.2.13, fabric-api-lookup-api-v1@1.1.0+1d383bb63d, fabric-screen-handler-api-v1@1.1.8+a02b44633d, improved-stations@2.0.5, beaconoverhaul@1.4.0+1.17, bitsandchisels@2.5.0, modmenu@2.0.0-beta.7, greater_eye@1.2.4, ducts@1.1.0, toolstats@2.0.1, cloth-utils-v1@2.0.54, invisiblights@7.1+1.17, fabric-tool-attribute-api-v1@1.2.12+b7ab61213d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10, editsign@2.2.1, enchant_giver@1.1.0, cloth-client-events-v0@2.0.54, blockus@2.2.0+1.17-rc1, fabric-crash-report-info-v1@0.1.5+be9da3103d, fabric-events-interaction-v0@0.4.8+a02b44633d, mostructures@1.2.0-pre1+mc.1.17, mcsa@2.3.2-1.17, fabric-language-kotlin@1.6.1+kotlin.1.5.10, origins@1.0.0, cullleaves@2.2.0, fabric-key-binding-api-v1@1.0.4+a02b44633d, cloth-config2@5.0.34, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0, mocolors@1.2.0, fabric-resource-loader-v0@0.4.7+b7ab6121a0, betterthirdperson@1.5.0, seamless_loading_screen@1.3.5+1.17, org_jetbrains_kotlin_kotlin-reflect@1.5.10, expandedstorage@7.0.0-alpha.25, particle_emitter_biom4st3r@0.1.0, cardinal-components-entity@3.0.0-nightly.21w19a, libblockattributes_fluids@0.9.0-pre.2, architectury@2.0.9, fabric-commands-v0@0.2.2+92519afa3d, fabric-registry-sync-v0@0.7.10+e2961fee3d, slotlock@1.0.4-BETA+1.17, cardinal-components-base@3.0.0-nightly.21w19a, adorn@2.0.0+1.17, fabric-mining-levels-v0@0.1.3+92519afa3d, fabric-networking-api-v1@1.0.11+b7ab61213d, earthtojavamobs@1.7.1+1.17, fabric-models-v0@0.3.0+a02b44633d, fabric-item-groups-v0@0.2.10+b7ab61213d, darkpaintings@3.0.6, truerooms@1.1.4, terraform-shapes-api-v1@1.0.4, fabric-renderer-api-v1@0.4.3+676f40fa3d, wandering_collector@1.0.2+mc1.17, inventorysorter@1.7.9-1.17, libcd@3.0.3+1.16.3, cardinal-components-block@3.0.0-nightly.1.17-pre2, grindenchantments@1.1.4+1.17, fabric-structure-api-v1@1.1.11+e36969833d, easyautocrafting@1.1+1.17, xlpackets@1.1, moenchantments@1.17.0, fabric-containers-v0@0.1.12+a02b44633d, lithium@0.7.0, fabric-object-builder-api-v1@1.10.9+b7ab61213d, caelus@0.0.16-1.17, waystones@2.0.1, libblockattributes@0.9.0-pre.2, pipe@1.3.1, mcdw@3.2.2-1.17, medievalweapons@1.1.5, comforts@0.0.4-1.17, dual_riders@1.0.5, fabric-rendering-data-attachment-v1@0.1.5+a02b44633d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1, mcda@1.6.2, pandamc_concreteplus@1.8, fabric-textures-v0@1.0.6+a02b44633d, cardinal-components-item@3.0.0-nightly.1.17-pre2, fabric-rendering-fluids-v1@0.1.13+a02b44633d, reach-entity-attributes@2.1.1, bedspreads@1.4.0-1.17, cloth-scissors-api-v1@2.0.54, fabric-lifecycle-events-v1@1.4.4+a02b44633d, cardinal-components-chunk@3.0.0-nightly.1.17-pre2, fabric-renderer-registries-v1@3.2.0+a02b44633d, cardinal-components-util@3.0.0-nightly.1.17-pre2, fabric-loot-tables-v1@1.0.4+a02b44633d, croptosis@1.1.2, moenchant_lib@0.1.0, trinketshulkerboxes@2.0.0-1.17, fabric-particles-v1@0.2.4+a02b44633d, libblockattributes_core@0.9.0-pre.2, fastchest@1.2+1.17, fabric-networking-blockentity-v0@0.2.11+a02b44633d, minecraft@1.17, voicechat@1.17-1.0.5, fabric-command-api-v1@1.1.1+a02b44633d, jankson@3.0.1+j1.2.0, cloth-basic-math@0.5.1, universal_ores@1.0, amecsapi@1.1.5+mc21w16a, fabric-screen-api-v1@1.0.4+155f865c3d, origins-classes@1.2.1, betterdroppeditems@1.3.0-1.17, fabric-renderer-indigo@0.4.8+a02b44633d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0, libninepatch@1.1.0, fabric-item-api-v1@1.2.4+a02b44633d, calio@1.0.0, roughlyenoughitems@6.0.251-alpha, kyrptconfig@1.1.10-1.17, cardinal-components@3.0.0-nightly.1.17-pre2, libgui@4.0.0+1.17, somnus@0.0.12-1.17, biome_locator@1.1.2, fabric-entity-events-v1@1.1.0+a02b44633d, fabric-rendering-v0@1.1.2+92519afa3d, croptopia@${mod_version}, fabric-rendering-v1@1.6.0+a02b44633d, omega-config@${version}, givemehats@1.6, entityculling@1.2.3, fabric-content-registries-v0@0.2.2+a02b44633d, trinketofundying@2.0.0-1.17, cardinal-components-world@3.0.0-nightly.1.17-pre2, fabric-tag-extensions-v0@1.1.4+a02b4463d5, blue_endless_jankson@1.2.1, fabric-biome-api-v1@3.1.11+c345aea83d, fastfurnace@1.17-3.0, advanced_runtime_resource_pack@0.2.9, ltr@1.1.11+1.17, kirin@1.8.7-1.17, cloth-api@2.0.54, betterf3@1.1.5, cloth-datagen-api-v1@2.0.54, carrier@1.8.0, fabric-events-lifecycle-v0@0.2.1+92519afa3d, fabric-object-builders-v0@0.7.3+a02b44633d, tweed@3.0.0-beta.22, secretrooms@1.0.0+1.17, presencefootsteps@r31-1.17-rc1
[17:11:09] [main/WARN]: Mod `consistency_plus` (0.3.3-build.261_UNMINIFIED) does not respect SemVer - comparison support is limited.
[17:11:09] [main/WARN]: Mod `croptopia` (${mod_version}) does not respect SemVer - comparison support is limited.
[17:11:09] [main/WARN]: Mod `omega-config` (${version}) does not respect SemVer - comparison support is limited.
[17:11:09] [main/WARN]: Mod `presencefootsteps` (r31-1.17-rc1) does not respect SemVer - comparison support is limited.
[17:11:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/Minecraf/Install/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[17:11:10] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[17:11:10] [main/INFO]: Compatibility level set to JAVA_16
[17:11:10] [main/INFO]: Loaded configuration file for Lithium: 77 options available, 0 override(s) found
[17:11:10] [main/WARN]: Reference map 'addendum-refmap.json' for addendum.mixins.json could not be read. If this is a development environment you can ignore this message
[17:11:10] [main/WARN]: Reference map 'ducts-refmap.json' for ducts.mixins.json could not be read. If this is a development environment you can ignore this message
[17:11:10] [main/ERROR]: [LTR] Error while writing configuration file: java.io.IOException: The system cannot find the path specified
[17:11:10] [main/ERROR]: [LTR] Could not read/write config! Stacktrace: java.io.FileNotFoundException: E:\Minecraf\Instances\KrypticPack\config\powertaters\liltaterreloaded\ltr.properties (The system cannot find the path specified)
[17:11:10] [main/WARN]: Reference map 'GreaterEye-Fabric-1.17-refmap.json' for greater_eye.mixins.json could not be read. If this is a development environment you can ignore this message
[17:11:10] [main/ERROR]: [LTR] Error while writing configuration file: java.io.IOException: The system cannot find the path specified
[17:11:10] [main/ERROR]: [LTR] Could not read/write config! Stacktrace: java.io.FileNotFoundException: E:\Minecraf\Instances\KrypticPack\config\powertaters\liltaterreloaded\ltr.properties (The system cannot find the path specified)
[17:11:10] [main/ERROR]: [LTR] Error while writing configuration file: java.io.IOException: The system cannot find the path specified
[17:11:10] [main/ERROR]: [LTR] Could not read/write config! Stacktrace: java.io.FileNotFoundException: E:\Minecraf\Instances\KrypticPack\config\powertaters\liltaterreloaded\ltr.properties (The system cannot find the path specified)
[17:11:10] [main/ERROR]: [LTR] Error while writing configuration file: java.io.IOException: The system cannot find the path specified
[17:11:10] [main/ERROR]: [LTR] Could not read/write config! Stacktrace: java.io.FileNotFoundException: E:\Minecraf\Instances\KrypticPack\config\powertaters\liltaterreloaded\ltr.properties (The system cannot find the path specified)
[17:11:10] [main/ERROR]: [LTR] Error while writing configuration file: java.io.IOException: The system cannot find the path specified
[17:11:10] [main/ERROR]: [LTR] Could not read/write config! Stacktrace: java.io.FileNotFoundException: E:\Minecraf\Instances\KrypticPack\config\powertaters\liltaterreloaded\ltr.properties (The system cannot find the path specified)
[17:11:10] [main/ERROR]: [LTR] Error while writing configuration file: java.io.IOException: The system cannot find the path specified
[17:11:10] [main/ERROR]: [LTR] Could not read/write config! Stacktrace: java.io.FileNotFoundException: E:\Minecraf\Instances\KrypticPack\config\powertaters\liltaterreloaded\ltr.properties (The system cannot find the path specified)
[17:11:11] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[17:11:11] [main/FATAL]: Mixin prepare failed preparing TradeOfferRegistrar in ltr.mixins.trading.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException java.lang.NullPointerException: Cannot read field "enableTaterTrading" because "mods.ltr.config.LilTaterReloadedConfig.ltrConfig" is null
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.NullPointerException: Cannot read field "enableTaterTrading" because "mods.ltr.config.LilTaterReloadedConfig.ltrConfig" is null
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:876) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
Caused by: java.lang.NullPointerException: Cannot read field "enableTaterTrading" because "mods.ltr.config.LilTaterReloadedConfig.ltrConfig" is null
	at mods.ltr.config.LilTaterReloadedConfig.isTaterTradingEnabled(LilTaterReloadedConfig.java:158) ~[LilTaterReloaded-1.1.11+1.17-RUSHED-E3-EDITION.jar:?]
	at mods.ltr.mixins.plugins.LilTaterTradingMixinPlugin.shouldApplyMixin(LilTaterTradingMixinPlugin.java:8) ~[LilTaterReloaded-1.1.11+1.17-RUSHED-E3-EDITION.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:978) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:943) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	... 23 more

```

**Comment by Yoghurt4C** [comment]
the config didn't generate so it crashed, let's see if that's my fuckup

**Comment by Yoghurt4C** [comment]
it works perfectly fine in a devenv, does the actual file get created in the first place?

**Comment by Yoghurt4C** [comment]
alright, adding it into an actual mmc instance broke everything. that's highly worrisome

**Comment by Yoghurt4C** [comment]
fixed in https://github.com/Yoghurt4C/LilTaterReloaded/commit/d8d880650b64ee07311ea88007718ca7283c1fc3; please get [this](https://github.com/Yoghurt4C/LilTaterReloaded/releases/download/v1.1.12/LilTaterReloaded-1.1.12+1.17.jar) jar if you still covet the tuberous totems

**Comment by KavisKryptic** [comment]
Thanks for the fix!
